//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace deAndrade_Project_II.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesStaff
    {
        public SalesStaff()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Full_Time { get; set; }
        public Nullable<System.DateTime> Hire_Date { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public int Employee_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
